### PR TITLE
switched to relative import of social so it works in python3

### PR DESCRIPTION
**Pull request by rtrajano**
I'm not entirely sure if the whole project will work in Python3 but this import was stopping me from loading the module in Python3.

### CODE REVIEW

**Comment by rdegges** [comment]
Thank you, we should have been doing this anyhow.

**Comment by rdegges** [comment]
Just cut a new release with this included. Thanks a ton =)

**Comment by rtrajano** [comment]
thanks! now i can remove this silly entry from my requirements file
`-e git://github.com/rtrajano/stormpath-django.git#egg=stormpath-django-master`

**Comment by rdegges** [comment]
=)

**Pull request merged**
