### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by skolsuper**
Fixes incompatible arguments being passed from django-rest-framework-jwt to StormpathBackend.authenticate, and changed unexpected behavious (no return value) of StormpathUserManager.create

### CODE REVIEW

**Comment by denibertovic** [comment]
Hi @skolsuper, just a small nitpick, can you update the PR with this small change:

    def authenticate(self, username=None, password=None, **kwargs):
        if username is None:
            username = kwargs.get(UserModel.USERNAME_FIELD)
        ....

**Comment by skolsuper** [comment]
No problem

**Comment by denibertovic** [comment]
@skolsuper awesome tnx! :+1:  @rdegges this looks ready for merge.

**Comment by rdegges** [comment]
Thanks @skolsuper for the codez <333

I just pushed a new release to PyPI (0.0.4) with these fixes included. You're also in the changelog! https://github.com/stormpath/stormpath-django#version-004

**Pull request merged**
